spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/stockapp
spring.datasource.username=postgres
spring.datasource.password=Rowlet123@#
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true